name: Pages

on:
  push:
    branches:
      - main # default branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      - name: Use Node.js 19.8.1
        uses: actions/setup-node@v2
        with:
          node-version: '19.8.1'
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public
      # - name: Upload to Personal Server
      #   if: env.SSH_PRIVATE_KEY != ''
      #   run: |
      #     if [ -z "${{ vars.SERVER_PORT }}" ] || \
      #       [ -z "${{ vars.SERVER_USER }}" ] || \
      #       [ -z "${{ vars.SERVER_ADDRESS }}" ] || \
      #       [ -z "${{ vars.SERVER_PAGE_PATH }}" ]; then
      #       echo "One or more required variables are empty"
      #       exit 1
      #     fi
      #     ssh -p ${{ vars.SERVER_PORT }} ${{ vars.SERVER_USER }}@${{ vars.SERVER_ADDRESS }} mkdir -p ${{ vars.SERVER_PAGE_PATH }}
      #     exit
      #     scp -P ${{ vars.SERVER_PORT }} -r ./public/* ${{ vars.SERVER_USER }}@${{ vars.SERVER_ADDRESS }}:${{ vars.SERVER_PAGE_PATH }}
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Upload to Personal Server
        if: env.SSH_PRIVATE_KEY && env.SERVER_USER && env.SERVER_ADDRESS && env.SERVER_PORT && env.SERVER_PAGE_PATH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ vars.SERVER_ADDRESS }}
          username: ${{ vars.SERVER_USER }}
          port: ${{ vars.SERVER_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./public/*"
          target: ${{ vars.SERVER_PAGE_PATH }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ${{ vars.SERVER_USER }}
          SERVER_ADDRESS: ${{ vars.SERVER_ADDRESS }}
          SERVER_PORT: ${{ vars.SERVER_PORT }}
          SERVER_PAGE_PATH: ${{ vars.SERVER_PAGE_PATH }}
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2